language: ruby
sudo: false
cache: bundler

rvm:
 - 2.3.3

branches:
  only:
    - master
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - RUN=html_proofer
    - RUN=test
    - RUN=lint

script: 'script/ci.rb'
